name: Mesa-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependency
      run: |
        wget https://gitlab.com/trivoxel-utils/deb-pacman/uploads/460d83f8711c1ab5e16065e57e7eeabc/deb-pacman-2.0-0.deb
        sudo dpkg -i deb-pacman-2.0-0.deb
        wget http://launchpadlibrarian.net/619293808/libalpm13_6.0.1-4_amd64.deb
        wget http://launchpadlibrarian.net/564413289/pkgconf_1.8.0-1_amd64.deb
        wget http://launchpadlibrarian.net/619293809/makepkg_6.0.1-4_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/d/directx-headers/directx-headers-dev_1.611.0-1_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/l/llvm-defaults/llvm_15.0-56~exp2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/universe/l/llvm-defaults/llvm-runtime_15.0-56~exp2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/w/wayland-protocols/wayland-protocols_1.31-1_all.deb
        sudo dpkg -i libalpm13_6.0.1-4_amd64.deb
        sudo apt install ./pkgconf_1.8.0-1_amd64.deb
        sudo apt remove llvm-13-dev
        sudo apt install meson ninja-build libvdpau-dev glslang-tools libomxil-bellagio-dev libva-dev libdrm-dev libdrm-intel1 libudev-dev llvm llvm-15 llvm-15-dev
        sudo apt install libelf-dev libglvnd-dev libunwind-dev libwayland-egl-backend-dev libxfixes-dev libxcb-glx0-dev libxxf86vm-dev libsensors-dev
        sudo apt install libx11-xcb-dev libxcb-keysyms1-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-present-dev libxshmfence-dev libxrandr-dev
        sudo apt install ./directx-headers-dev_1.611.0-1_amd64.deb
        sudo apt install ./llvm-runtime_15.0-56~exp2_amd64.deb
        sudo apt install ./llvm_15.0-56~exp2_amd64.deb
        sudo apt install ./wayland-protocols_1.31-1_all.deb
        pip install Mako
        sudo dpkg -i makepkg_6.0.1-4_amd64.deb
        pacman --version
    - name: Download Build
      run: |
        curl "https://aur.archlinux.org/cgit/aur.git/snapshot/mesa-git.tar.gz" -o mesa-git.tar.gz
        tar -xvf mesa-git.tar.gz
        cp PKGBUILD mesa-git/PKGBUILD
    - name: Build
      run: |
        cd mesa-git
        makepkg -so
        cd src/mesa
        git config --global user.email "firdiansyaindrianto@gmail.com"
        git config --global user.name "cari-404"
        curl -L "https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/26165.patch" | git am
        cd ../..
        makepkg -sei
