name: Mesa-Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependency
      run: |
        wget https://gitlab.com/trivoxel-utils/deb-pacman/uploads/460d83f8711c1ab5e16065e57e7eeabc/deb-pacman-2.0-0.deb
        sudo dpkg -i deb-pacman-2.0-0.deb
        wget http://launchpadlibrarian.net/619293808/libalpm13_6.0.1-4_amd64.deb
        wget http://launchpadlibrarian.net/564413289/pkgconf_1.8.0-1_amd64.deb
        wget http://launchpadlibrarian.net/619293809/makepkg_6.0.1-4_amd64.deb
        sudo dpkg -i libalpm13_6.0.1-4_amd64.deb
        sudo apt install ./pkgconf_1.8.0-1_amd64.deb
        sudo apt install meson ninja-build directx-headers-dev
        sudo dpkg -i makepkg_6.0.1-4_amd64.deb
        pacman --version
    - name: Download Build
      run: |
        curl "https://aur.archlinux.org/cgit/aur.git/snapshot/mesa-git.tar.gz" -o mesa-git.tar.gz
        tar -xvf mesa-git.tar.gz
    - name: Build
      run: |
        cd mesa-git
        makepkg -so
        cd src/mesa
        git config --global user.email "firdiansyaindrianto@gmail.com"
        git config --global user.name "cari-404"
        curl -L "https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/26165.patch" | git am
        cd ../..
        makepkg -sei
